apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-electronics:203afadcb105bd441b5e3ddb3a6e2a94f8b54f23
        ports:
        - containerPort: 80
