apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlemusic:e8a23ace21dbf4e41fce11b7da113fb68cd0706b
        ports:
        - containerPort: 80
