apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-computers:f01febfe47229538dea824eed418d03cf178f554
        ports:
        - containerPort: 80
