apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 396606070456.dkr.ecr.ap-northeast-1.amazonaws.com/shopping-site-googlegrocery:e8a23ace21dbf4e41fce11b7da113fb68cd0706b
        ports:
        - containerPort: 80
